### ISSUE TITLE
Criar tela de login

### ISSUE THREAD

**Issue by jcserracampos** [guildatech/site#11]

**Comment by CoderSquirrel** [comment]
Prototipo :
![prototipologin](https://user-images.githubusercontent.com/6757777/64267858-1e33ad00-cf05-11e9-9956-2a4db24425a7.png)

Figma também atualizado já

**Comment by jcserracampos** [comment]
@CoderSquirrel acho que pode não exibir o menu na tela de login e cadastro.
Que tal?

**Comment by CoderSquirrel** [comment]
![prototipologin](https://user-images.githubusercontent.com/6757777/64299736-4b557f00-cf48-11e9-8175-e4b788fcac27.png)
Que tal @jcserracampos ?

**Comment by iagocavalcante** [comment]
Achei muito bom!

**Comment by jcserracampos** [comment]
Perfeito!
