### ISSUE TITLE
UIKit

### ISSUE THREAD

**Issue by CoderSquirrel** [guildatech/site#3]
Interessante discutirmos qual UIKIT usaremos, bootstrap, bulma, material, fundation, creative tim... e afins

**Comment by onlurking** [comment]
Voto em usarmos [Bulma](https://bulma.io)

**Comment by CoderSquirrel** [comment]
Eu gosto bastante dos uikits feitos pelo @criativetim tem alguns ja com os componentes montados pros frameworks
